site_name: Bald Money
site_url: https://baldmoney.com

theme:
  name: material
  logo: images/logo.png
  features:
    - navigation.tabs
  font:
    text: Bitter

nav:
  - index.md
  - Blog:
      - blog/index.md
  - Best Of:
    - Best International Money Transfer Services: best-of/best-forex.md
    - Best High Interest Savings Account: best-of/savings-account.md
    - Best NASDAQ 100 ETF: best-of/best-nasdaq100-etf.md
  - Retirement Rip-Off:
    - Are You Being Screwed By Your Retirement Fund?: screwed-by-superfund.md
    - Best Super/Retirement Fund (Australia): best-super-fund.md
  - investment-fees-calculator.md
  - contribute.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-JS1TPL3F0D

plugins:
  - blog:
      categories: true
  - search